# Generated by Django 4.1.7 on 2023-03-09 08:39

import blog.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_mymodel_post_publish_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blog.storages.MediaStorage(), upload_to='media'),
        ),
    ]
