# Generated by Django 4.1.7 on 2023-03-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
