# Generated by Django 4.1.7 on 2023-03-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_delete_file_alter_post_image_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
