# Generated by Django 4.1.7 on 2023-03-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_comment_post_remove_fileversion_file_delete_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
