# Generated by Django 4.1.7 on 2023-03-31 06:52

import blog.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_file_fileversion_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=blog.storages.MediaStorage(), upload_to='uploads/'),
        ),
    ]
