# Generated by Django 4.1.7 on 2023-03-31 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_post_remove_fileversion_file_delete_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosyaVersiyonu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='dosyalar/')),
                ('zaman', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YüklenenDosya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='dosyalar/')),
                ('zaman', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='dosyaversiyonu',
            name='yuklenen_dosya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiyonlar', to='post.yüklenendosya'),
        ),
    ]
