# Generated by Django 4.1.7 on 2023-04-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_dosyaversiyonu_yüklenendosya_delete_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_versions', to='post.document')),
            ],
        ),
        migrations.DeleteModel(
            name='DosyaVersiyonu',
        ),
        migrations.DeleteModel(
            name='YüklenenDosya',
        ),
    ]
