# Generated by Django 4.1.7 on 2023-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_document_delete_dosyaversiyonu_delete_yüklenendosya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='media/'),
        ),
    ]
